#!/bin/zsh
#SBATCH -n 4 # Number of cores
#SBATCH -N 1
#SBATCH -D /home/jbrugues/multilingual-scene-text-vqa/src/
#SBATCH -p dcc # or mlow Partition to submit to master low prioriy queue
#SBATCH --mem 16384
#SBATCH --gres gpu:Pascal:1 # Para pedir Pascales MAX 8
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to wh

#python eval.py --batch_size 1 --language zh --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_zh_original_evaluatedInZH --model_to_evaluate outputs/models/estvqa_wiki_zh_original --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language en --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_zh_original_evaluatedInEN --model_to_evaluate outputs/models/estvqa_wiki_zh_original --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language en --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_zh_original_evaluatedInENTranslated --model_to_evaluate outputs/models/estvqa_wiki_zh_original --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_translated_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language zh --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_zh_original_evaluatedInZHTranslated --model_to_evaluate outputs/models/estvqa_wiki_zh_original --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_translated_subsample_all_answers.json --no_server_evaluation

#python eval.py --batch_size 1 --language zh --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_zh_translated_evaluatedInZH --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_zh_translated --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_translated_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language en --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_zh_translated_evaluatedInEN --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_zh_translated --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_translated_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language zh --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_zh_translated_evaluatedInEN_Not_Translated --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_zh_translated --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language en --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_zh_translated_evaluatedInEN_Not_Translated --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_zh_translated --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_subsample_all_answers.json --no_server_evaluation

#python eval.py --batch_size 1 --language zh --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_original_evaluatedInZH --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_en_original --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language en --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_original_evaluatedInEN --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_en_original --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language zh --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_original_evaluatedInZH_Translated --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_en_original --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_translated_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language en --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_original_evaluatedInEN_Translatedf --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_en_original --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_translated_subsample_all_answers.json --no_server_evaluation

#python eval.py --batch_size 1 --language en --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_translated_evaluatedInEN --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_en_translated --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_translated_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language zh --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_translated_evaluatedInZH --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_en_translated --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_translated_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language en --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_translated_evaluatedInEN_Not_Translated --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_en_translated --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language zh --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_translated_evaluatedInZH_Not_Translated --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_en_translated --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_subsample_all_answers.json --no_server_evaluation
#
#python eval.py --batch_size 1 --language zh --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_zh_original_evaluatedInZH --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_en_zh_original --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language en --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_zh_original_evaluatedInEN --dataset estvqa --model_to_evaluate outputs/models/estvqa_wiki_en_zh_original --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language zh --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_zh_original_evaluatedInZH_Translated --model_to_evaluate outputs/models/estvqa_wiki_en_zh_original --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_translated_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language en --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_zh_original_evaluatedInEN_Translated --model_to_evaluate outputs/models/estvqa_wiki_en_zh_original --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_translated_subsample_all_answers.json --no_server_evaluation

#python eval.py --batch_size 1 --language zh --embedding_type bpemb --bpemb_subtype multi --output_folder estvqa_bpemb_en_zh_original_evaluatedInZH --dataset estvqa --model_to_evaluate outputs/models/estvqa_bpemb_en_zh_original --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language en --embedding_type bpemb --bpemb_subtype multi --output_folder estvqa_bpemb_en_zh_original_evaluatedInEN --dataset estvqa --model_to_evaluate outputs/models/estvqa_bpemb_en_zh_original --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language zh --embedding_type bpemb --bpemb_subtype multi --output_folder estvqa_bpemb_en_zh_original_evaluatedInZH_Translated --dataset estvqa --model_to_evaluate outputs/models/estvqa_bpemb_en_zh_original --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_translated_subsample_all_answers.json --no_server_evaluation
#python eval.py --batch_size 1 --language en --embedding_type bpemb --bpemb_subtype multi --output_folder estvqa_bpemb_en_zh_original_evaluatedInEN_Translated --dataset estvqa --model_to_evaluate outputs/models/estvqa_bpemb_en_zh_original --image_path data/EST-VQA-v1.0 --gt_eval_file data/EST-VQA-v1.0/annotations/eval_translated_subsample_all_answers.json --no_server_evaluation


#python train.py --language zh --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_zh_original --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_file data/EST-VQA-v1.0/annotations/train_subsample_all_answers.json
python train.py --language zh --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_zh_translated --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_file data/EST-VQA-v1.0/annotations/train_translated_subsample_all_answers.json
#
#python train.py --language en --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_original --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_file data/EST-VQA-v1.0/annotations/train_subsample_all_answers.json
#python train.py --language en --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_translated --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_file data/EST-VQA-v1.0/annotations/train_translated_subsample_all_answers.json
#
#python train.py --language en-zh --embedding_type fasttext --fasttext_subtype wiki --output_folder estvqa_wiki_en_zh_original --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_file data/EST-VQA-v1.0/annotations/train_subsample_all_answers.json
#python train.py --language en-zh --embedding_type bpemb --bpemb_subtype multi --output_folder estvqa_bpemb_en_zh_original --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_file data/EST-VQA-v1.0/annotations/train_subsample_all_answers.json
python train.py --language en --embedding_type bpemb --bpemb_subtype multi --output_folder estvqa_bpemb_en_original --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_file data/EST-VQA-v1.0/annotations/train_subsample_all_answers.json
python train.py --language zh --embedding_type bpemb --bpemb_subtype multi --output_folder estvqa_bpemb_zh_original --dataset estvqa --image_path data/EST-VQA-v1.0 --gt_file data/EST-VQA-v1.0/annotations/train_subsample_all_answers.json
